ecommerce/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from .views import *


urlpatterns = [
    # path('', home, name='home'),
    path('', products, name='home'),
    path('wishlist/', view_wishlist, name='view_wishlist'),
    path('products/', products, name='products'),
    path('new-products/', newest_products, name='newest_products'),
    path('low-price-products/', low_price_products, name='low_price_products'),
    path('high-price-products/', high_price_products, name='high_price_products'),
    path('product/<slug:slug>/', product, name='product'),
    path('about/', about, name='about'),
    path('contact/', contact_us, name='contact'),
    path('cart/', cart, name='cart'),
    path('customer-account/', account, name='customer_account'),

    path('add-to-cart/<slug:slug>/', add_to_cart, name='add-to-cart'),
    path('add-to-wishlist/<int:pk>/', add_to_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<int:pk>/', remove_from_wishlist, name='remove_from_wishlist'),
    # path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug:slug>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-from-cart/<slug:slug>/', reduce_from_cart, name='reduce-from-cart'),
    # path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
        #  name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', payment, name='payment'),
    # path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('checkout/', checkout, name='checkout'),
    # path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('create-payment-intent/', create_checkout_session, name='create-checkout'),
]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce/core/models.py
from django.db import models
from django.shortcuts import reverse
# from django.db.models.signals import post_save
from django.conf import settings
from django.db.models import Sum
from django.utils import timezone
from django.utils.text import slugify

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Category(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    # def get_absolute_url(self):
    #     return reverse("categories", kwargs={})

    def __str__(self):
        return self.title


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='category')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    # def get_absolute_url(self):
    #     return reverse("sub_categories", kwargs={})

    def __str__(self):
        return self.title


class Item(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField(blank=True, null=True)
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Item, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_add_to_wishlist_url(self):
        return reverse("add_to_wishlist", kwargs={
            'pk': self.id
        })

    def remove_from_wishlist_url(self):
        return reverse("remove_from_wishlist", kwargs={
            'pk': self.id
        })

    def get_remove_from_cart_url(self):
        return reverse("remove-from-cart", kwargs={
            'slug': self.slug
        })

    def get_reduce_from_cart_url(self):
        return reverse("reduce-from-cart", kwargs={
            'slug': self.slug
        })


class Wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)


# Cart...
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


# Check out...
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    # ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    address = models.ForeignKey(
        'Address', related_name='address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.OneToOneField(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.email

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


ORDER_STATUS = (
    ('P', 'Processing'),
    ('S', 'Shipping'),
    ('D', 'Delivered'),
    ('R', 'Refunded'),
)
PAYMENT_STATUS = (
    ('C', 'CashOnDelivery'),
    ('P', 'Paid'),
)


class ManageOrder(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    status = models.CharField(choices=ORDER_STATUS, max_length=1, default='P')
    payment = models.CharField(choices=PAYMENT_STATUS, max_length=1,default='P')

    def __str__(self):
        return self.order.user.email


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    shipping_address = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=11, null=True)
    zip = models.CharField(max_length=100)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.shipping_address

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

ecommerce/templates/about.html
 {% extends 'base.html' %}
 {% block title %}
    <title>About Us</title>
    
    {% endblock title %}
 {% block content %}
      {% include 'nav.html' %}

    <!-- About Page Starts Here -->
    <div class="about-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>About Us</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-image">
              <img src="assets/images/about-us.jpg" alt="">
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>Phasellus vel interdum elit</h4>
              <p><a href="https://www.pexels.com/photo/group-of-people-raising-right-hand-1059120/">Photo Credit</a> goes to Pexels website. Aliquam erat volutpat. Pellentesque fringilla, ligula consectetur cursus scelerisque, leo elit pellentesque sapien, et pharetra arcu elit vitae sem. Suspendisse erat dui, condimentum in mi ac, varius tempor sapien. Donec in justo sit amet ex aliquet maximus ac quis erat.</p> 
              <br>
              <p>Donec fermentum tincidunt tellus quis fermentum. Proin eget imperdiet purus. Nulla facilisi. Aliquam tincidunt porttitor dui sed euismod. Duis est libero, rhoncus fermentum turpis id, tempus fringilla ipsum. Nullam venenatis tincidunt neque vel hendrerit. Suspendisse porta pretium porttitor.</p>
              <br>
              <p>Sed purus quam, ultricies eu leo in, sollicitudin varius quam. Proin dictum urna ac diam fermentum tempus. Pellentesque urna urna, ullamcorper a tincidunt dignissim, venenatis in nisi. Vivamus in volutpat tellus. Etiam fermentum luctus posuere.</p>
              <br>
              <p><a rel="nofollow" href="https://www.tooplate.com/view/2114-pixie">Pixie HTML Template</a> can be converted into your desired CMS theme. You can use this Bootstrap v4.1.3 layout for any online shop. Please tell your friends about <a rel="nofollow" href="https://www.facebook.com/tooplate/">Tooplate</a>. Thank you.</p>
              <div class="share">
                <h6>Find us on: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->

    
{% endblock content %}
{% block script  %}

    

{% endblock script  %}

ecommerce/templates/ac-nav.html
   
   
   {% load static %}
    {% load custom_tags  %}
   <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href={% url 'home' %}><img src={% static "assets/images/header-logo.png" %} alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
              <a class="nav-link" href={% url 'home' %}>Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href= {% url 'customer_account' %}>Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href= {% url 'view_wishlist' %}>Wishlist({{user|wishlist_total}})</a>
            </li>
           
            <li class="nav-item">
              <a class="nav-link" href={% url 'account_login' %}>Reviews</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href= {% url 'about' %}>Profile</a>
            </li>
           
            <li class="nav-item">
              <a class="nav-link" href={% url 'account_logout' %}>SignOut</a>
            </li>

            <li class="nav-item">
              <a class="nav-link d-inline-flex" href={% url 'cart' %}>
                <span class="material-icons">shopping_cart</span>
                {% if user.is_authenticated %}
                  {{user|total_cart_items}}
                {% else %}
                  {{request.session.order_item|total_cart_items_}}
                {% endif %}
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

ecommerce/templates/banner.html

    <!-- Banner Starts Here -->
    <div class="banner">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="caption">
              <h2>Ecommerce HTML Template</h2>
              <div class="line-dec"></div>
              <p>Pixie HTML Template can be converted into your desired CMS theme. Total <strong>5 pages</strong> included. You can use this Bootstrap v4.1.3 layout for any CMS. 
              <br><br>Please tell your friends about <a rel="nofollow" href="https://www.facebook.com/tooplate/">Tooplate</a> free template site. Thank you. Photo credit goes to <a rel="nofollow" href="https://www.pexels.com">Pexels website</a>.</p>
              <div class="main-button">
                <a href="#">Order Now!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->

ecommerce/templates/cart.html
{% extends "base.html" %}
{% load custom_tags %}

{% block content %}
      {% include 'nav.html' %}
    <br>    <br>    <br>
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
    {% comment %} {% for order_item in object.items.all %} {% endcomment %}
    {% for order_item in object|items_all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            {% comment %} <td>{{ order_item.item.title }}</td>  {% endcomment %}
            <td><a href='{% url 'product' order_item.item.slug %}'>{{ order_item.item.title }}</a></td>
            <td>{{ order_item.item.price }}</td>
            <td >
                <a href={{ order_item.item.get_reduce_from_cart_url }} class='mr-2'> <span class="material-icons">remove_circle</span></a>
                <b>
                {{ order_item.quantity }}

                </b>
                <a href="{{ order_item.item.get_add_to_cart_url }}" class='ml-2'><span class="material-icons">add_circle</span></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price|floatformat:2 }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved|floatformat:2 }}</span>
            {% else %}
                ${{ order_item.get_total_item_price|floatformat:2 }}
            {% endif %}
            <a style='color: red;' href="{{ order_item.item.get_remove_from_cart_url }}">
            <span class="material-icons ml-3">delete</span>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
    {% endfor %}
        
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total|floatformat:2 }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

    <br>    <br>    <br>
  
{% endblock content %}


ecommerce/templates/checkout.html
{% extends "base.html" %}

{% block content %}
      {% include 'ac-nav.html' %}
  <br><br><br>

<div class="container ">
  <main>
   
     <div class="row ">
        <div class="col-md-7 col-lg-8">
       
          {% if address %}
            <h6>Default Shipping Address:</h6>
            <p class="ml-2">{{address.shipping_address}}</p>
            <p class="ml-2">{{address.phone}}</p>
          {% else %}
          <div class="alert alert-warning" role="alert">
          You have no default Shipping Address!
          </div>
        {% endif %}
        </div>

      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Shipping address</h4>
        <form class="needs-validation" method='POST' >
        {% csrf_token %}
          <div class="row g-3">
           
            <div class="col-12 mb-2">
              <label for="address" class="form-label">Address</label>
              
              <input name='shipping_address' type="text" class="form-control" id="address" placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-12 mb-2">
              <label for="phone" class="form-label">Contact Number </label>
              <input name='phone' type="text" class="form-control" id="phone" placeholder="01. . ." required>
            </div> 

            <div class="col-md-4">
              <label for="zip" class="form-label">Zip</label>
              <input name='zip' type="text" class="form-control" id="zip" placeholder="" required>
              <div class="invalid-feedback">
                Zip code required.
              </div>
            </div>
          </div>

          <hr class="my-4">

          <div class="form-check">
            <input name='shipping' value='N' type="radio" class="form-check-input" id="same-address" required>
            <label class="form-check-label" for="same-address">Set new default shipping address</label>
          </div>

          {% if address %}
          <div class="form-check">
            <input name='shipping' value='D' type="radio" class="form-check-input" id="save-info" required>
            <label class="form-check-label" for="save-info">Use default shipping address</label>
          </div>
          {% endif %}<br>



          <hr class="my-4">

          <h4 class="mb-3">Payment</h4>

          <div class="my-3">
            {% comment %} <div class="form-check">
              <input id="credit" name="payment_option" value='C' type="radio" class="form-check-input" checked required>
              <label class="form-check-label" for="credit">Card</label>
            </div> {% endcomment %}
            <div class="form-check">
              <input id="stripe" name="payment_option" value='S'  type="radio" class="form-check-input" required>
              <label class="form-check-label" for="debit">Stripe</label>
            </div>
            <div class="form-check">
              <input id="paypal" name="payment_option" value='P'  type="radio" class="form-check-input" required>
              <label class="form-check-label" for="paypal">PayPal</label>
            </div>
            <div class="form-check">
              <input id="cash" name="payment_option" value='C'  type="radio" class="form-check-input" required>
              <label class="form-check-label" for="paypal">Cash On Delivery</label>
            </div>
          </div>


          <hr class="my-4">

          <button id="continue" class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
        </form>
      </div>
    </div>
  </main>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2017–2021 Company Name</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>
</div>
{% endblock content %}
{% block script  %}
<script>  

document.getElementById('save-info').addEventListener("click", function(){
  document.getElementById('address').required=false
  document.getElementById('phone').required=false
  document.getElementById('zip').required=false

})
document.getElementById('same-address').addEventListener("click", function(){
document.getElementById('address').required=true
document.getElementById('phone').required=true
document.getElementById('zip').required=true

})
document.getElementById('cash').addEventListener("click", function(){
document.getElementById('continue').innerHTML='Place Order'

})
</script>

{% endblock script  %}

ecommerce/templates/featured-items.html
    
    {% load static %}
    <!-- Featured Starts Here -->
    <div class="featured-items">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Featured Items</h1>
            </div>
          </div>
          <div class="col-md-12">
            <div class="owl-carousel owl-theme">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src={% static "assets/images/item-01.jpg" alt="Item 1"%}>
                  <h4>Proin vel ligula</h4>
                  <h6>$15.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src={% static "assets/images/item-02.jpg" alt="Item 2"%}>
                  <h4>Erat odio rhoncus</h4>
                  <h6>$25.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src={% static "assets/images/item-03.jpg" alt="Item 3"%}>
                  <h4>Integer vel turpis</h4>
                  <h6>$35.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src={% static "assets/images/item-04.jpg" alt="Item 4"%}>
                  <h4>Sed purus quam</h4>
                  <h6>$45.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src={% static "assets/images/item-05.jpg" alt="Item 5"%}>
                  <h4>Morbi aliquet</h4>
                  <h6>$55.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src={% static "assets/images/item-06.jpg" alt="Item 6"%}>
                  <h4>Urna ac diam</h4>
                  <h6>$65.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src={% static "assets/images/item-04.jpg" alt="Item 7"%}>
                  <h4>Proin eget imperdiet</h4>
                  <h6>$75.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src={% static "assets/images/item-05.jpg" alt="Item 8"%}>
                  <h4>Nullam risus nisl</h4>
                  <h6>$85.00</h6>
                </div>
              </a>
              <a href="single-product.html">
                <div class="featured-item">
                  <img src={% static "assets/images/item-06.jpg" alt="Item 9"%}>
                  <h4>Cras tempus</h4>
                  <h6>$95.00</h6>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Featred Ends Here -->


ecommerce/templates/footer.html
    {% load static %}
    <!-- Footer Starts Here -->
    <div class="footer">
      <div class="container">
        <div class="row">
          
          <div class="col-md-12">
            <div class="footer-menu">
              <ul>
                <li><a href={% url 'home' %}>Home</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href={% url 'contact' %}>Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-12">
            <div class="social-icons">
              <ul>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-rss"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Footer Ends Here -->

 <!-- Sub Footer Starts Here -->
    <div class="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="copyright-text">
              <p>Copyright &copy; 2019 Company Name : <a rel="nofollow" href="#">RABBANI</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Sub Footer Ends Here -->

     

ecommerce/templates/home.html
 {% extends 'base.html' %}

   {% block title %}<title>Home</title>{% endblock title %}

   {% block content %}
      {% include 'nav.html' %}
      {% include 'banner.html' %}
      {% include 'featured-items.html' %}
   {% endblock content %}









ecommerce/templates/page-navigation.html
    
    
    
    <div class="page-navigation">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul>
              <li class="current-page"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

ecommerce/templates/product.html
{% extends "base.html" %}
    {% block title %}
    <title>Product Detail.</title>
    
    {% endblock title %}

{% block content %}
      {% include 'nav.html' %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt=""> {% endcomment %}
          <img src={{ object.image.url}} class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                {% comment %} <span class="badge purple mr-1">{{ object.get_category_display }}</span> {% endcomment %}
                <span class="badge purple mr-1">{{ object.title }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            {% if item_in_cart %}
              <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                Remove from cart
              </a>
            {% else %}
              <a href="{{ object.get_add_to_wishlist_url }}" class="btn btn-danger btn-md my-0 p">
                Add to wishlist
              </a>
            {% endif %}
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}
{% block script %}
<script>

function Hide() {
  document.getElementById("mess").style.visibility="hidden";
  //console.log('hi');
}

document.getElementById("add-to-cart").onclick = function() {

  window.localStorage.setItem("item", "{{object.slug}}" );

};













</script>


{% endblock script %}